name: image_slider_preview_example
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  image_slider_preview:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
