name: image_slider_preview
description: A Flutter image slider with indicator and full screen image preview with zoom support.
version: 0.0.3

homepage: https://github.com/seifyaser/image_preview_slider_pakacge
repository: https://github.com/seifyaser/image_preview_slider_pakacge

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
